export const seedProducts = [
  {
    name: 'Celeste Diamond Ring',
    slug: 'celeste-diamond-ring',
    sku: 'AUR-RNG-001',
    description: 'An exquisite 18K yellow gold solitaire diamond ring featuring a brilliant 1.2 carat round brilliant diamond with pave diamond band accents.',
    price: 48900,
    discountPrice: 44900,
    category: 'Rings',
    collectionName: 'Diamond Essentials',
    metal: '18K Gold',
    stone: 'Solitaire Diamond',
    weight: '4.2g',
    sizes: ['5', '6', '7', '8', '9'],
    stock: 12,
    images: ['/assets/category_rings.jpg'],
    rating: 4.9,
    reviewsCount: 18,
    isFeatured: true,
    isNewArrival: true,
    specifications: {
      karatage: '18K Gold (750)',
      diamondClarity: 'VVS1',
      diamondColor: 'E',
      certification: 'IGI Certified & BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Aurelia Gold Necklace',
    slug: 'aurelia-gold-necklace',
    sku: 'AUR-NCK-002',
    description: 'A timeless 18K yellow gold chain holding a graceful pear-cut diamond surrounded by a delicate diamond halo.',
    price: 76500,
    discountPrice: 69900,
    category: 'Necklaces',
    collectionName: 'Everyday Gold',
    metal: '18K Gold',
    stone: 'Natural Diamond',
    weight: '7.8g',
    sizes: ['16 inch', '18 inch', '20 inch'],
    stock: 8,
    images: ['/assets/category_necklaces.jpg'],
    rating: 5.0,
    reviewsCount: 24,
    isFeatured: true,
    isNewArrival: true,
    specifications: {
      karatage: '18K Gold (750)',
      diamondClarity: 'VVS2',
      diamondColor: 'F',
      certification: 'IGI Certified & BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Élan Diamond Earrings',
    slug: 'elan-diamond-earrings',
    sku: 'AUR-ERG-003',
    description: 'Captivating 18K gold drop earrings crafted with intricate diamond clusters designed to catch light from every angle.',
    price: 52000,
    discountPrice: null,
    category: 'Earrings',
    collectionName: 'Statement Pieces',
    metal: '18K Gold',
    stone: 'Natural Diamond',
    weight: '5.5g',
    sizes: ['Standard'],
    stock: 15,
    images: ['/assets/category_earrings.jpg'],
    rating: 4.8,
    reviewsCount: 14,
    isFeatured: true,
    isNewArrival: true,
    specifications: {
      karatage: '18K Gold (750)',
      diamondClarity: 'VS1',
      diamondColor: 'G',
      certification: 'BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Solara Gold Bracelet',
    slug: 'solara-gold-bracelet',
    sku: 'AUR-BRC-004',
    description: 'A luxurious 18K gold tennis bracelet inlaid with round brilliant diamonds, secured with a custom safety clasp.',
    price: 62300,
    discountPrice: 58500,
    category: 'Bracelets',
    collectionName: 'Timeless Classics',
    metal: '18K Gold',
    stone: 'Natural Diamond',
    weight: '9.4g',
    sizes: ['Small (6.5")', 'Medium (7.0")', 'Large (7.5")'],
    stock: 7,
    images: ['/assets/category_bracelets.jpg'],
    rating: 4.9,
    reviewsCount: 11,
    isFeatured: true,
    isNewArrival: false,
    specifications: {
      karatage: '18K Gold (750)',
      diamondClarity: 'VVS2',
      diamondColor: 'F',
      certification: 'IGI Certified & BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Noor Royal Bridal Set',
    slug: 'noor-royal-bridal-set',
    sku: 'AUR-BDL-005',
    description: 'A magnificent heritage Indian bridal choker crafted with Kundan, uncut diamonds, and natural pearls.',
    price: 185000,
    discountPrice: 169000,
    category: 'Bridal',
    collectionName: 'The Bridal Edit',
    metal: '18K Gold',
    stone: 'Polki',
    weight: '48.5g',
    sizes: ['Custom Adjustable'],
    stock: 3,
    images: ['/assets/category_bridal.jpg'],
    rating: 5.0,
    reviewsCount: 32,
    isFeatured: true,
    isNewArrival: true,
    specifications: {
      karatage: '22K & 18K Gold',
      diamondClarity: 'Uncut Gem Grade Polki',
      diamondColor: 'Natural Warm',
      certification: 'BIS Hallmarked & Authenticity Card',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Sovereign Men\'s Gold Band',
    slug: 'sovereign-mens-gold-band',
    sku: 'AUR-MEN-006',
    description: 'A bold modern men\'s band engineered in 18K gold with deep matte black enamel inlay and a flush-set natural diamond.',
    price: 38500,
    discountPrice: null,
    category: "Men's",
    collectionName: 'Statement Pieces',
    metal: '18K Gold',
    stone: 'Natural Diamond',
    weight: '8.2g',
    sizes: ['8', '9', '10', '11', '12'],
    stock: 10,
    images: ['/assets/category_mens.jpg'],
    rating: 4.9,
    reviewsCount: 9,
    isFeatured: true,
    isNewArrival: true,
    specifications: {
      karatage: '18K Gold (750)',
      diamondClarity: 'VS1',
      diamondColor: 'G',
      certification: 'BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Aria Solitaire Platinum Ring',
    slug: 'aria-solitaire-platinum-ring',
    sku: 'AUR-RNG-007',
    description: 'Ultra-luxurious 950 Platinum ring featuring a certified 1.5 carat oval cut diamond held in a signature 4-prong claw setting.',
    price: 112000,
    discountPrice: 99000,
    category: 'Rings',
    collectionName: 'Diamond Essentials',
    metal: 'Platinum',
    stone: 'Solitaire Diamond',
    weight: '5.1g',
    sizes: ['5', '6', '7', '8'],
    stock: 5,
    images: ['/assets/hero_lifestyle.jpg'],
    rating: 5.0,
    reviewsCount: 16,
    isFeatured: false,
    isNewArrival: true,
    specifications: {
      karatage: 'Platinum 950',
      diamondClarity: 'IF - VVS1',
      diamondColor: 'D Color (Colorless)',
      certification: 'GIA Certified & BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Royal Heritage Emerald Choker',
    slug: 'royal-heritage-emerald-choker',
    sku: 'AUR-NCK-008',
    description: 'Grand statement gold choker studded with natural Zambian emeralds and brilliant white diamonds.',
    price: 145000,
    discountPrice: 132000,
    category: 'Necklaces',
    collectionName: 'The Bridal Edit',
    metal: '18K Gold',
    stone: 'Emerald',
    weight: '32.0g',
    sizes: ['Adjustable Silk Cord'],
    stock: 4,
    images: ['/assets/editorial_bridal.jpg'],
    rating: 4.9,
    reviewsCount: 8,
    isFeatured: true,
    isNewArrival: false,
    specifications: {
      karatage: '18K Yellow Gold',
      diamondClarity: 'VVS',
      diamondColor: 'F-G',
      certification: 'IGI Gemstone Report',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Lumina Sapphire Drop Earrings',
    slug: 'lumina-sapphire-drop-earrings',
    sku: 'AUR-ERG-009',
    description: 'Deep Ceylon blue sapphire drop earrings encased in delicate 18K white gold diamond halos.',
    price: 68000,
    discountPrice: null,
    category: 'Earrings',
    collectionName: 'Statement Pieces',
    metal: 'White Gold',
    stone: 'Sapphire',
    weight: '6.1g',
    sizes: ['Standard Drop'],
    stock: 6,
    images: ['/assets/category_earrings.jpg'],
    rating: 4.8,
    reviewsCount: 7,
    isFeatured: false,
    isNewArrival: true,
    specifications: {
      karatage: '18K White Gold',
      diamondClarity: 'VVS2',
      diamondColor: 'F',
      certification: 'IGI Certified',
      warranty: 'Lifetime Guarantee'
    }
  },
  {
    name: 'Rose Gold Velvet Bangle',
    slug: 'rose-gold-velvet-bangle',
    sku: 'AUR-BRC-010',
    description: 'Smooth 18K rose gold open cuff bangle with pavé diamond terminal caps.',
    price: 42500,
    discountPrice: 39500,
    category: 'Bracelets',
    collectionName: 'Everyday Gold',
    metal: 'Rose Gold',
    stone: 'Natural Diamond',
    weight: '7.0g',
    sizes: ['2.4', '2.6', '2.8'],
    stock: 14,
    images: ['/assets/category_bracelets.jpg'],
    rating: 4.7,
    reviewsCount: 15,
    isFeatured: false,
    isNewArrival: false,
    specifications: {
      karatage: '18K Rose Gold',
      diamondClarity: 'VS1',
      diamondColor: 'G',
      certification: 'BIS Hallmarked',
      warranty: 'Lifetime Guarantee'
    }
  }
];

export const seedCoupons = [
  {
    code: 'AURELIA10',
    discountPercentage: 10,
    minOrderValue: 25000,
    expiryDate: new Date('2027-12-31')
  },
  {
    code: 'BRIDAL15',
    discountPercentage: 15,
    minOrderValue: 100000,
    expiryDate: new Date('2027-12-31')
  }
];
